In [1]:
from sqlalchemy import create_engine, text
import os
from dotenv import load_dotenv

engine = create_engine(f'postgresql://{os.getenv('DB_USER')}:{os.getenv('DB_PASSWORD')}@localhost:5432/f1pace')

# Импорт данных

In [48]:
import pandas as pd

laps = pd.read_sql("SELECT * FROM laps ORDER BY session_id, driver_id, lap_number", engine)

In [ ]:
import pandas as pd

laps_cleaned = pd.read_sql("SELECT * FROM laps_cleaned ORDER BY session_id, driver_id, lap_number", engine)

In [3]:
laps

,id,session_id,driver_id,position,session_time_start,session_time_end,pit_in_session_time,pit_out_session_time,lap_time,lap_s1_time,lap_s2_time,lap_s3_time,lap_number,stint_number,tyre_age,tyre_type,is_deleted,track_status
0,57,299,32,1.0,2229.970,2348.393,NaN,NaN,118.245,NaN,53.703,32.579,1,1.0,4.0,2,False,4
1,58,299,32,1.0,2348.393,2490.799,NaN,NaN,142.406,45.874,61.922,34.610,2,1.0,5.0,2,False,4
2,59,299,32,1.0,2490.799,2648.778,NaN,NaN,NaN,44.111,62.264,51.626,3,1.0,6.0,2,False,4
3,60,299,32,1.0,2648.778,2753.121,NaN,NaN,104.343,32.129,41.273,30.941,4,1.0,7.0,2,False,6
4,61,299,32,1.0,2753.121,2857.750,NaN,NaN,104.629,39.328,41.460,23.841,5,1.0,8.0,2,False,6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
139120,138664,884,95,14.0,8600.150,8694.448,NaN,NaN,94.298,33.060,35.245,25.993,52,2.0,24.0,3,False,1
139121,138665,884,95,14.0,8694.448,8791.791,NaN,NaN,97.343,32.961,38.400,25.982,53,2.0,25.0,3,False,1
139122,138666,884,95,14.0,8791.791,8886.623,NaN,NaN,94.832,33.526,35.336,25.970,54,2.0,26.0,3,False,1
139123,138667,884,95,14.0,8886.623,8981.105,NaN,NaN,94.482,33.071,35.335,26.076,55,2.0,27.0,3,False,1
139124,138668,884,95,14.0,8981.105,9086.047,NaN,NaN,104.942,35.663,40.132,29.147,56,2.0,28.0,3,False,2

# Новые столбцы

Новые столбцы is_first_lap, is_last_lap (именно для пилота, а не в гонке в целом), is_pit_in_lap, is_pit_out_lap (считается любой заезд на пит-лейн кроме схода)

In [49]:
laps_cleaned = laps.copy()

In [50]:
laps_cleaned["is_first_lap"] = laps_cleaned.apply(lambda row : True if row["lap_number"] == 1 else False, axis=1)

In [51]:
laps_cleaned["is_last_lap"] = False
last_laps = laps_cleaned.groupby(["session_id", "driver_id"])["id"].last().values
for last_lap_id in last_laps:
    laps_cleaned.loc[laps_cleaned["id"] == last_lap_id, "is_last_lap"] = True

In [52]:
laps_cleaned["is_pit_out_lap"] = False
pit_in_laps = laps_cleaned.groupby(["session_id", "driver_id"])["stint_number"].diff()

laps_cleaned.loc[(pit_in_laps > 0), "is_pit_out_lap"] = True

In [53]:
laps_cleaned["is_pit_in_lap"] = False

mask = laps_cleaned["is_pit_out_lap"].shift(-1) == True

laps_cleaned.loc[mask, "is_pit_in_lap"] = True

In [10]:
laps_cleaned.to_sql("laps_cleaned", engine, if_exists='replace', index=False)

125

# Заполнение пропусков времен

In [54]:
def fill_lap_time(row):
    lap_time = row["lap_time"]
    lap_s1_time = row["lap_s1_time"]
    lap_s2_time = row["lap_s2_time"]
    lap_s3_time = row["lap_s3_time"]

    if pd.isna(lap_time) and not pd.isna(lap_s1_time) and not pd.isna(lap_s2_time) and not pd.isna(lap_s3_time):
        row["lap_time"] = lap_s1_time + lap_s2_time + lap_s3_time
    elif not pd.isna(lap_time) and pd.isna(lap_s1_time) and not pd.isna(lap_s2_time) and not pd.isna(lap_s3_time):
        row["lap_s1_time"] = lap_time - lap_s2_time - lap_s3_time
    elif not pd.isna(lap_time) and not pd.isna(lap_s1_time) and pd.isna(lap_s2_time) and not pd.isna(lap_s3_time):
        row["lap_s2_time"] = lap_time - lap_s1_time - lap_s3_time
    elif not pd.isna(lap_time) and not pd.isna(lap_s1_time) and not pd.isna(lap_s2_time) and pd.isna(lap_s3_time):
        row["lap_s3_time"] = lap_time - lap_s1_time - lap_s2_time

    return row


# laps_cleaned = laps_cleaned.apply(fill_lap_time, axis=1)

Время круга всегда можно вычеслить через session_time, при этом в session_time нет пропусков

In [55]:
mask = (
    (~ pd.isna(laps["lap_time"])) & 
    ~(laps["lap_time"].round(3) == (laps["session_time_end"] - laps["session_time_start"]).round(3)) &
    (laps["driver_id"] == laps["driver_id"].shift()) & 
    (laps["session_id"] == laps["session_id"].shift())

)

laps[mask][["lap_number", "session_time_start", "session_time_end", "lap_time",]]

Empty DataFrame
Columns: [lap_number, session_time_start, session_time_end, lap_time]
Index: []

In [56]:
print(len(laps[(pd.isna(laps["session_time_start"]))]))
print(len(laps[(pd.isna(laps["session_time_end"]))]))

0
0

In [57]:
len(laps[(pd.isna(laps["lap_time"]))])

2841

In [58]:
mask = (
    (pd.isna(laps_cleaned["lap_time"]))
)

laps_cleaned.loc[mask, "lap_time"] = laps_cleaned.loc[mask, "session_time_end"] - laps_cleaned.loc[mask, "session_time_start"]
laps_cleaned

,id,session_id,driver_id,position,session_time_start,session_time_end,pit_in_session_time,pit_out_session_time,lap_time,lap_s1_time,...,lap_number,stint_number,tyre_age,tyre_type,is_deleted,track_status,is_first_lap,is_last_lap,is_pit_out_lap,is_pit_in_lap
0,57,299,32,1.0,2229.970,2348.393,NaN,NaN,118.245,NaN,...,1,1.0,4.0,2,False,4,True,False,False,False
1,58,299,32,1.0,2348.393,2490.799,NaN,NaN,142.406,45.874,...,2,1.0,5.0,2,False,4,False,False,False,False
2,59,299,32,1.0,2490.799,2648.778,NaN,NaN,157.979,44.111,...,3,1.0,6.0,2,False,4,False,False,False,False
3,60,299,32,1.0,2648.778,2753.121,NaN,NaN,104.343,32.129,...,4,1.0,7.0,2,False,6,False,False,False,False
4,61,299,32,1.0,2753.121,2857.750,NaN,NaN,104.629,39.328,...,5,1.0,8.0,2,False,6,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
139120,138664,884,95,14.0,8600.150,8694.448,NaN,NaN,94.298,33.060,...,52,2.0,24.0,3,False,1,False,False,False,False
139121,138665,884,95,14.0,8694.448,8791.791,NaN,NaN,97.343,32.961,...,53,2.0,25.0,3,False,1,False,False,False,False
139122,138666,884,95,14.0,8791.791,8886.623,NaN,NaN,94.832,33.526,...,54,2.0,26.0,3,False,1,False,False,False,False
139123,138667,884,95,14.0,8886.623,8981.105,NaN,NaN,94.482,33.071,...,55,2.0,27.0,3,False,1,False,False,False,False
139124,138668,884,95,14.0,8981.105,9086.047,NaN,NaN,104.942,35.663,...,56,2.0,28.0,3,False,2,False,True,False,False

In [59]:
len(laps_cleaned[(pd.isna(laps_cleaned["lap_time"]))])

0

In [60]:
laps_cleaned.to_sql("laps_cleaned", engine, if_exists='replace', index=False)

125

# Просмотр пропусков

In [42]:
laps_filled[pd.isna(laps_filled["position"])]

,id,session_id,driver_abbr,driver_num,position,lap_time,lap_s1_time,lap_s2_time,lap_s3_time,lap_number,...,tyre_age,tyre_type,is_deleted,air_temp,track_temp,humidity,is_rain,wind_direction,wind_speed,track_status
1026,1027,299,MAZ,9,NaN,NaN,NaN,NaN,NaN,1,...,1.0,2,False,20.5,28.1,53.8,False,13,1.1,4
1905,1906,304,LAT,6,NaN,NaN,NaN,NaN,NaN,1,...,1.0,4,False,9.5,17.2,75.7,True,199,0.1,2
1936,1937,304,RUS,63,NaN,NaN,NaN,NaN,NaN,31,...,5.0,2,False,11.1,15.9,66.5,False,155,0.5,4
2030,2031,304,BOT,77,NaN,NaN,NaN,NaN,NaN,31,...,6.0,2,False,11.1,15.9,66.5,False,155,0.5,4
3203,3204,309,RAI,7,NaN,NaN,NaN,NaN,NaN,2,...,2.0,1,False,20.0,40.0,37.9,False,8,1.0,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
135937,135938,874,STR,18,NaN,NaN,NaN,NaN,NaN,10,...,10.0,3,False,15.5,22.8,55.4,False,96,1.9,4
135938,135939,874,ALB,23,NaN,NaN,NaN,NaN,NaN,1,...,1.0,3,False,15.6,22.5,55.3,False,102,4.5,2
136316,136317,874,BOR,5,NaN,NaN,NaN,NaN,NaN,1,...,1.0,3,False,15.6,22.5,55.3,False,102,4.5,2
136539,136540,874,PIA,81,NaN,NaN,NaN,NaN,NaN,1,...,1.0,2,False,15.6,22.5,55.3,False,102,4.5,2
137702,137703,879,BEA,87,NaN,NaN,NaN,NaN,NaN,21,...,5.0,3,False,18.5,32.7,51.5,False,107,0.4,4

In [3]:
columns = ["id", "session_id", "driver_num", "position", 
           "lap_time", "lap_s1_time","lap_s2_time" ,"lap_s3_time" ,"lap_number", 
           "is_first_lap", "is_last_lap", "is_pit_in_lap", "is_pit_out_lap"]

In [13]:
mask = (
    (pd.isna(laps_filled["lap_time"])) | 
    (pd.isna(laps_filled["lap_s1_time"])) |
    (pd.isna(laps_filled["lap_s2_time"])) |
    (pd.isna(laps_filled["lap_s3_time"])) 
)

mask = mask & (laps_filled["is_first_lap"] == False)
mask = mask & (laps_filled["is_last_lap"] == False)
mask = mask & (laps_filled["is_pit_in_lap"] == False)
mask = mask & (laps_filled["is_pit_out_lap"] == False)

laps_filled[mask][columns].to_csv("nan_time.csv")

In [14]:
laps_filled[mask][columns]

,id,session_id,driver_num,position,lap_time,lap_s1_time,lap_s2_time,lap_s3_time,lap_number,is_first_lap,is_last_lap,is_pit_in_lap,is_pit_out_lap
1782,1783,304,5,17.0,144.647,46.123,NaN,NaN,2,False,False,False,False
8559,8560,334,18,6.0,71.251,NaN,NaN,NaN,6,False,False,False,False
8561,8562,334,18,6.0,71.553,NaN,NaN,21.838,8,False,False,False,False
11021,11022,343,11,19.0,107.519,29.120,NaN,NaN,5,False,False,False,False
21302,21303,379,7,12.0,114.741,NaN,NaN,34.711,52,False,False,False,False
25691,25692,399,31,2.0,NaN,NaN,30.035,29.412,17,False,False,False,False
32745,32746,439,6,17.0,NaN,30.896,51.097,NaN,29,False,False,False,False
36301,36302,458,5,19.0,99.114,17.428,NaN,NaN,10,False,False,False,False
72494,72494,609,1,1.0,NaN,NaN,32.183,21.411,36,False,False,False,False
72684,72684,609,16,2.0,NaN,NaN,32.794,21.445,36,False,False,False,False
80463,80463,644,1,1.0,NaN,NaN,42.768,18.603,3,False,False,False,False
80516,80516,644,11,2.0,NaN,NaN,42.877,18.696,3,False,False,False,False
80569,80569,644,55,4.0,NaN,NaN,43.105,18.553,3,False,False,False,False
80675,80675,644,4,3.0,NaN,NaN,43.152,18.525,3,False,False,False,False
80728,80728,644,14,5.0,NaN,NaN,43.268,18.703,3,False,False,False,False
80940,80940,644,22,9.0,NaN,NaN,NaN,NaN,3,False,False,False,False
93233,93233,694,24,20.0,NaN,31.343,NaN,38.281,3,False,False,False,False
99946,99946,724,10,9.0,115.050,NaN,NaN,34.459,6,False,False,False,False
100511,100511,724,14,13.0,84.127,NaN,NaN,21.376,11,False,False,False,False
108950,108950,764,63,2.0,96.207,NaN,NaN,NaN,38,False,False,False,False
108951,108951,764,63,2.0,96.398,NaN,NaN,NaN,39,False,False,False,False
108952,108952,764,63,2.0,96.471,NaN,NaN,NaN,40,False,False,False,False
108953,108953,764,63,2.0,96.391,NaN,NaN,NaN,41,False,False,False,False
108954,108954,764,63,2.0,96.280,NaN,NaN,NaN,42,False,False,False,False
108955,108955,764,63,2.0,96.665,NaN,NaN,NaN,43,False,False,False,False
108956,108956,764,63,2.0,96.885,NaN,NaN,NaN,44,False,False,False,False
108957,108957,764,63,2.0,96.746,NaN,NaN,NaN,45,False,False,False,False
108958,108958,764,63,2.0,96.456,NaN,NaN,NaN,46,False,False,False,False
108959,108959,764,63,2.0,96.708,NaN,NaN,NaN,47,False,False,False,False
108960,108960,764,63,2.0,96.746,NaN,NaN,NaN,48,False,False,False,False
108961,108961,764,63,2.0,97.315,NaN,NaN,NaN,49,False,False,False,False
108962,108962,764,63,2.0,96.973,NaN,NaN,NaN,50,False,False,False,False
108963,108963,764,63,2.0,97.377,NaN,NaN,NaN,51,False,False,False,False
108964,108964,764,63,2.0,97.281,NaN,NaN,NaN,52,False,False,False,False
108965,108965,764,63,2.0,97.412,NaN,NaN,NaN,53,False,False,False,False
108966,108966,764,63,2.0,97.369,NaN,NaN,NaN,54,False,False,False,False
108967,108967,764,63,2.0,97.387,NaN,NaN,NaN,55,False,False,False,False
108968,108968,764,63,2.0,97.844,NaN,NaN,NaN,56,False,False,False,False

Пропуски позиций только на последних кругах, при этом если пропущена позиция, то и пропущено время круга

In [38]:
mask = (
    (~pd.isna(laps_filled["position"])) &  
    (pd.isna(laps_filled["lap_time"]))
)

laps_filled[mask][["session_id", "driver_abbr", "position", "lap_number", "lap_time", "track_status"]]

        session_id driver_abbr  position  lap_number  lap_time  track_status
1059           304         GAS      14.0          33       NaN             5
1123           304         PER       4.0          34       NaN             1
1185           304         ALO      12.0          33       NaN             5
1249           304         LEC       2.0          34       NaN             1
1311           304         STR       7.0          33       NaN             5
...            ...         ...       ...         ...       ...           ...
135584         872         HAD       9.0           1       NaN             2
135603         872         RUS       1.0           1       NaN             2
135622         872         BOT      21.0           1       NaN             2
135634         872         PIA       5.0           1       NaN             2
135653         872         BEA       7.0           1       NaN             2

[876 rows x 6 columns]

In [12]:
mask = (
    (pd.isna(laps_filled["lap_time"])) &
    (laps_filled["is_last_lap"] == False)
)

columns = ["session_id", "driver_abbr", "position", 
           "lap_time", "lap_s1_time","lap_s2_time" ,"lap_s3_time" ,"lap_number", "track_status",
           "is_first_lap", "is_last_lap", "is_pit_in_lap", "is_pit_out_lap"]

laps_filled[mask][columns].to_csv("nan_times.csv")