In [1]:
from sqlalchemy import create_engine, text
import os
from dotenv import load_dotenv

engine = create_engine(f'postgresql://{os.getenv('DB_USER')}:{os.getenv('DB_PASSWORD')}@localhost:5432/f1pace')

# Импорт данных

In [2]:
import pandas as pd

laps = pd.read_sql("SELECT * FROM laps", engine)

In [2]:
import pandas as pd

laps_filled = pd.read_sql("SELECT * FROM laps_cleaned", engine)

In [3]:
laps

,id,session_id,driver_abbr,driver_num,position,lap_time,lap_s1_time,lap_s2_time,lap_s3_time,lap_number,...,tyre_age,tyre_type,is_deleted,air_temp,track_temp,humidity,is_rain,wind_direction,wind_speed,track_status
0,1,299,HAM,44,2.0,119.538,NaN,54.367,32.463,1,...,4.0,2,False,20.5,28.1,53.8,False,13,1.1,4
1,2,299,HAM,44,2.0,142.712,46.763,61.387,34.562,2,...,5.0,2,False,20.5,27.9,54.5,False,8,1.0,4
2,3,299,HAM,44,2.0,NaN,43.739,62.116,50.801,3,...,6.0,2,False,20.5,27.9,54.7,False,13,0.9,4
3,4,299,HAM,44,2.0,104.932,32.339,41.826,30.767,4,...,7.0,2,False,20.5,27.9,54.7,False,35,0.6,6
4,5,299,HAM,44,2.0,105.139,39.813,41.410,23.916,5,...,8.0,2,False,20.5,28.1,54.2,False,8,0.8,6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
137698,137699,879,BEA,87,19.0,117.448,57.139,41.840,18.469,17,...,1.0,3,False,18.8,32.8,48.7,False,100,1.3,1
137699,137700,879,BEA,87,19.0,96.054,35.006,42.424,18.624,18,...,2.0,3,False,18.7,32.5,48.8,False,78,1.2,1
137700,137701,879,BEA,87,18.0,95.905,35.345,42.252,18.308,19,...,3.0,3,False,18.6,32.2,49.2,False,58,1.8,1
137701,137702,879,BEA,87,18.0,95.604,35.253,42.310,18.041,20,...,4.0,3,False,18.6,32.6,49.9,False,116,0.9,1
137702,137703,879,BEA,87,NaN,NaN,NaN,NaN,NaN,21,...,5.0,3,False,18.5,32.7,51.5,False,107,0.4,4

# Заполнение пропусков времен

In [6]:
def fill_lap_time(row):
    lap_time = row["lap_time"]
    lap_s1_time = row["lap_s1_time"]
    lap_s2_time = row["lap_s2_time"]
    lap_s3_time = row["lap_s3_time"]

    if pd.isna(lap_time) and not pd.isna(lap_s1_time) and not pd.isna(lap_s2_time) and not pd.isna(lap_s3_time):
        row["lap_time"] = lap_s1_time + lap_s2_time + lap_s3_time
    elif not pd.isna(lap_time) and pd.isna(lap_s1_time) and not pd.isna(lap_s2_time) and not pd.isna(lap_s3_time):
        row["lap_s1_time"] = lap_time - lap_s2_time - lap_s3_time
    elif not pd.isna(lap_time) and not pd.isna(lap_s1_time) and pd.isna(lap_s2_time) and not pd.isna(lap_s3_time):
        row["lap_s2_time"] = lap_time - lap_s1_time - lap_s3_time
    elif not pd.isna(lap_time) and not pd.isna(lap_s1_time) and not pd.isna(lap_s2_time) and pd.isna(lap_s3_time):
        row["lap_s3_time"] = lap_time - lap_s1_time - lap_s2_time

    return row


laps_filled = laps.apply(fill_lap_time, axis=1)

In [25]:
mask = (laps_filled["lap_s1_time"] + laps_filled["lap_s2_time"] + laps_filled["lap_s3_time"]).round(3) != laps_filled["lap_time"].round(3)
mask = (
    mask & 
    (~ pd.isna(laps_filled["lap_time"])) & 
    (~ pd.isna(laps_filled["lap_s1_time"])) &
    (~ pd.isna(laps_filled["lap_s2_time"])) &
    (~ pd.isna(laps_filled["lap_s3_time"]))
)

laps_filled[mask]

Empty DataFrame
Columns: [id, session_id, driver_abbr, driver_num, position, lap_time, lap_s1_time, lap_s2_time, lap_s3_time, lap_number, stint_number, tyre_age, tyre_type, is_deleted, air_temp, track_temp, humidity, is_rain, wind_direction, wind_speed, track_status]
Index: []

[0 rows x 21 columns]

In [19]:
bad_laps = laps_filled[mask]
bad_laps["delta"] = bad_laps["lap_time"] - (bad_laps["lap_s1_time"] + bad_laps["lap_s2_time"] + bad_laps["lap_s3_time"])
bad_laps[["lap_time", "lap_s1_time", "lap_s2_time", "lap_s3_time", "delta"]]

/tmp/ipykernel_3132/3218247130.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bad_laps["delta"] = bad_laps["lap_time"] - (bad_laps["lap_s1_time"] + bad_laps["lap_s2_time"] + bad_laps["lap_s3_time"])

        lap_time  lap_s1_time  lap_s2_time  lap_s3_time  delta
13143     84.840       27.932       28.621       28.279  0.008
102174    95.717       27.305       31.481       36.418  0.513
102175    96.360       27.520       31.784       36.547  0.509
102224    95.877       27.327       31.860       36.176  0.514
102274    96.139       27.399       31.926       36.299  0.515
102323    96.031       27.647       31.964       35.910  0.510
102324    96.333       28.033       31.943       35.846  0.511
102374    96.929       27.674       31.948       36.794  0.513
102428    94.876       26.777       31.506       36.089  0.504
102469    97.188       27.960       32.278       36.438  0.512
102923    96.980       27.778       31.918       36.771  0.513
102924    97.106       27.830       31.940       36.823  0.513
102974   114.485       45.354       32.035       36.584  0.512
103017    99.608       29.896       32.362       36.841  0.509
103022    96.762       27.660       31.959       36.625  0.518

In [26]:
laps_filled.loc[mask, "lap_time"] = laps_filled.loc[mask, "lap_s1_time"] + laps_filled.loc[mask, "lap_s2_time"] + laps_filled.loc[mask, "lap_s3_time"]
laps_filled[mask]

Empty DataFrame
Columns: [id, session_id, driver_abbr, driver_num, position, lap_time, lap_s1_time, lap_s2_time, lap_s3_time, lap_number, stint_number, tyre_age, tyre_type, is_deleted, air_temp, track_temp, humidity, is_rain, wind_direction, wind_speed, track_status]
Index: []

[0 rows x 21 columns]

In [28]:
laps_filled.to_sql("laps_cleaned", engine, if_exists='append', index=False)

703

# Проверка на порядок

In [41]:
diffs = laps_filled.groupby(['session_id', 'driver_num'])['lap_number'].diff()
is_sorted = (diffs.dropna() > 0).all()

is_sorted

np.True_

In [36]:
laps_filled[diffs <= 0]

,id,session_id,driver_abbr,driver_num,position,lap_time,lap_s1_time,lap_s2_time,lap_s3_time,lap_number,...,tyre_age,tyre_type,is_deleted,air_temp,track_temp,humidity,is_rain,wind_direction,wind_speed,track_status
122809,122808,819,HAM,44,7.0,83.037,32.056,27.712,23.269,1,...,1.0,2,False,20.7,29.3,68.0,False,226,1.2,1

Один круг идет не попорядку, но его можно удалить, так как это все равно последний круг в гонке для этого пилота

In [37]:
laps_filled[(laps_filled["session_id"] == 819) & (laps_filled["driver_num"] == 44)]

,id,session_id,driver_abbr,driver_num,position,lap_time,lap_s1_time,lap_s2_time,lap_s3_time,lap_number,...,tyre_age,tyre_type,is_deleted,air_temp,track_temp,humidity,is_rain,wind_direction,wind_speed,track_status
118566,122830,819,HAM,44,NaN,NaN,NaN,NaN,NaN,23,...,23.0,2,False,20.0,25.9,71.0,False,194,3.5,4
122809,122808,819,HAM,44,7.0,83.037,32.056,27.712,23.269,1,...,1.0,2,False,20.7,29.3,68.0,False,226,1.2,1
122810,122809,819,HAM,44,7.0,76.716,26.405,27.548,22.763,2,...,2.0,2,False,20.6,28.8,68.0,False,204,1.4,1
122811,122810,819,HAM,44,7.0,76.449,26.112,27.692,22.645,3,...,3.0,2,False,20.7,28.8,68.0,False,208,3.0,1
122812,122811,819,HAM,44,7.0,76.570,26.331,27.560,22.679,4,...,4.0,2,False,20.7,27.8,67.0,False,243,3.2,1
122813,122812,819,HAM,44,7.0,76.432,26.200,27.394,22.838,5,...,5.0,2,False,20.6,27.5,68.0,False,210,2.0,1
122814,122813,819,HAM,44,7.0,75.684,25.949,27.151,22.584,6,...,6.0,2,False,20.6,27.7,68.0,False,186,2.5,1
122815,122814,819,HAM,44,7.0,76.036,25.946,27.467,22.623,7,...,7.0,2,False,20.6,27.7,68.0,False,204,2.1,1
122816,122815,819,HAM,44,7.0,75.962,25.826,27.457,22.679,8,...,8.0,2,False,20.5,27.5,69.0,False,193,2.4,1
122817,122816,819,HAM,44,7.0,75.856,25.855,27.240,22.761,9,...,9.0,2,False,20.6,27.7,69.0,False,177,2.3,1
122818,122817,819,HAM,44,7.0,76.114,25.950,27.421,22.743,10,...,10.0,2,False,20.6,27.7,69.0,False,205,2.7,1
122819,122818,819,HAM,44,7.0,76.558,26.071,27.540,22.947,11,...,11.0,2,False,20.6,27.7,69.0,False,205,2.7,1
122820,122819,819,HAM,44,7.0,76.171,25.917,27.440,22.814,12,...,12.0,2,False,20.6,27.4,69.0,False,192,2.5,1
122821,122820,819,HAM,44,7.0,76.480,25.817,27.566,23.097,13,...,13.0,2,False,20.5,27.3,70.0,False,206,2.1,1
122822,122821,819,HAM,44,7.0,76.584,25.978,27.577,23.029,14,...,14.0,2,False,20.5,27.3,70.0,False,166,1.9,1
122823,122822,819,HAM,44,7.0,76.371,25.851,27.537,22.983,15,...,15.0,2,False,20.5,27.1,70.0,False,195,2.8,1
122824,122823,819,HAM,44,7.0,76.125,25.795,27.358,22.972,16,...,16.0,2,False,20.6,27.1,69.0,False,210,2.3,1
122825,122824,819,HAM,44,7.0,76.179,25.870,27.371,22.938,17,...,17.0,2,False,20.7,27.2,70.0,False,208,2.3,1
122826,122825,819,HAM,44,7.0,76.028,25.716,27.559,22.753,18,...,18.0,2,False,20.7,27.1,69.0,False,197,2.2,1
122827,122826,819,HAM,44,7.0,76.171,25.706,27.698,22.767,19,...,19.0,2,False,20.6,26.7,70.0,False,193,2.3,1
122828,122827,819,HAM,44,7.0,76.561,25.935,27.753,22.873,20,...,20.0,2,False,20.5,26.6,71.0,False,204,3.2,1
122829,122828,819,HAM,44,7.0,76.468,25.767,27.811,22.890,21,...,21.0,2,False,20.4,26.5,71.0,False,190,3.0,1
122830,122829,819,HAM,44,7.0,76.926,25.959,27.903,23.064,22,...,22.0,2,False,20.3,25.9,72.0,False,191,3.0,1

In [39]:
laps_filled = laps_filled.drop(118566, axis=0)

In [40]:
laps_filled.to_sql("laps_cleaned", engine, if_exists='replace', index=False)

702

# Новые столбцы

Новые столбцы is_first_lap, is_last_lap (именно для пилота, а не в гонке в целом), is_pit_in_lap, is_pit_out_lap (считается любой заезд на пит-лейн кроме схода)

In [46]:
laps_filled["is_first_lap"] = laps_filled.apply(lambda row : True if row["lap_number"] == 1 else False, axis=1)

In [58]:
laps_filled["is_last_lap"] = False
last_laps = laps_filled.groupby(["session_id", "driver_num"])["id"].last().values
for last_lap_id in last_laps:
    laps_filled.loc[laps_filled["id"] == last_lap_id, "is_last_lap"] = True

In [84]:
laps_filled["is_pit_out_lap"] = False
pit_in_laps = laps_filled.groupby(["session_id", "driver_num"])["stint_number"].diff()

laps_filled.loc[(pit_in_laps > 0), "is_pit_out_lap"] = True

In [91]:
laps_filled["is_pit_in_lap"] = False

mask = laps_filled["is_pit_out_lap"].shift(-1) == True

laps_filled.loc[mask, "is_pit_in_lap"] = True

In [96]:
laps_filled.to_sql("laps_cleaned", engine, if_exists='replace', index=False)

702

# Пропуски позиции

In [42]:
laps_filled[pd.isna(laps_filled["position"])]

,id,session_id,driver_abbr,driver_num,position,lap_time,lap_s1_time,lap_s2_time,lap_s3_time,lap_number,...,tyre_age,tyre_type,is_deleted,air_temp,track_temp,humidity,is_rain,wind_direction,wind_speed,track_status
1026,1027,299,MAZ,9,NaN,NaN,NaN,NaN,NaN,1,...,1.0,2,False,20.5,28.1,53.8,False,13,1.1,4
1905,1906,304,LAT,6,NaN,NaN,NaN,NaN,NaN,1,...,1.0,4,False,9.5,17.2,75.7,True,199,0.1,2
1936,1937,304,RUS,63,NaN,NaN,NaN,NaN,NaN,31,...,5.0,2,False,11.1,15.9,66.5,False,155,0.5,4
2030,2031,304,BOT,77,NaN,NaN,NaN,NaN,NaN,31,...,6.0,2,False,11.1,15.9,66.5,False,155,0.5,4
3203,3204,309,RAI,7,NaN,NaN,NaN,NaN,NaN,2,...,2.0,1,False,20.0,40.0,37.9,False,8,1.0,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
135937,135938,874,STR,18,NaN,NaN,NaN,NaN,NaN,10,...,10.0,3,False,15.5,22.8,55.4,False,96,1.9,4
135938,135939,874,ALB,23,NaN,NaN,NaN,NaN,NaN,1,...,1.0,3,False,15.6,22.5,55.3,False,102,4.5,2
136316,136317,874,BOR,5,NaN,NaN,NaN,NaN,NaN,1,...,1.0,3,False,15.6,22.5,55.3,False,102,4.5,2
136539,136540,874,PIA,81,NaN,NaN,NaN,NaN,NaN,1,...,1.0,2,False,15.6,22.5,55.3,False,102,4.5,2
137702,137703,879,BEA,87,NaN,NaN,NaN,NaN,NaN,21,...,5.0,3,False,18.5,32.7,51.5,False,107,0.4,4

In [3]:
columns = ["id", "session_id", "driver_num", "position", 
           "lap_time", "lap_s1_time","lap_s2_time" ,"lap_s3_time" ,"lap_number", 
           "is_first_lap", "is_last_lap", "is_pit_in_lap", "is_pit_out_lap"]

In [13]:
mask = (
    (pd.isna(laps_filled["lap_time"])) | 
    (pd.isna(laps_filled["lap_s1_time"])) |
    (pd.isna(laps_filled["lap_s2_time"])) |
    (pd.isna(laps_filled["lap_s3_time"])) 
)

mask = mask & (laps_filled["is_first_lap"] == False)
mask = mask & (laps_filled["is_last_lap"] == False)
mask = mask & (laps_filled["is_pit_in_lap"] == False)
mask = mask & (laps_filled["is_pit_out_lap"] == False)

laps_filled[mask][columns].to_csv("nan_time.csv")

In [14]:
laps_filled[mask][columns]

,id,session_id,driver_num,position,lap_time,lap_s1_time,lap_s2_time,lap_s3_time,lap_number,is_first_lap,is_last_lap,is_pit_in_lap,is_pit_out_lap
1782,1783,304,5,17.0,144.647,46.123,NaN,NaN,2,False,False,False,False
8559,8560,334,18,6.0,71.251,NaN,NaN,NaN,6,False,False,False,False
8561,8562,334,18,6.0,71.553,NaN,NaN,21.838,8,False,False,False,False
11021,11022,343,11,19.0,107.519,29.120,NaN,NaN,5,False,False,False,False
21302,21303,379,7,12.0,114.741,NaN,NaN,34.711,52,False,False,False,False
25691,25692,399,31,2.0,NaN,NaN,30.035,29.412,17,False,False,False,False
32745,32746,439,6,17.0,NaN,30.896,51.097,NaN,29,False,False,False,False
36301,36302,458,5,19.0,99.114,17.428,NaN,NaN,10,False,False,False,False
72494,72494,609,1,1.0,NaN,NaN,32.183,21.411,36,False,False,False,False
72684,72684,609,16,2.0,NaN,NaN,32.794,21.445,36,False,False,False,False
80463,80463,644,1,1.0,NaN,NaN,42.768,18.603,3,False,False,False,False
80516,80516,644,11,2.0,NaN,NaN,42.877,18.696,3,False,False,False,False
80569,80569,644,55,4.0,NaN,NaN,43.105,18.553,3,False,False,False,False
80675,80675,644,4,3.0,NaN,NaN,43.152,18.525,3,False,False,False,False
80728,80728,644,14,5.0,NaN,NaN,43.268,18.703,3,False,False,False,False
80940,80940,644,22,9.0,NaN,NaN,NaN,NaN,3,False,False,False,False
93233,93233,694,24,20.0,NaN,31.343,NaN,38.281,3,False,False,False,False
99946,99946,724,10,9.0,115.050,NaN,NaN,34.459,6,False,False,False,False
100511,100511,724,14,13.0,84.127,NaN,NaN,21.376,11,False,False,False,False
108950,108950,764,63,2.0,96.207,NaN,NaN,NaN,38,False,False,False,False
108951,108951,764,63,2.0,96.398,NaN,NaN,NaN,39,False,False,False,False
108952,108952,764,63,2.0,96.471,NaN,NaN,NaN,40,False,False,False,False
108953,108953,764,63,2.0,96.391,NaN,NaN,NaN,41,False,False,False,False
108954,108954,764,63,2.0,96.280,NaN,NaN,NaN,42,False,False,False,False
108955,108955,764,63,2.0,96.665,NaN,NaN,NaN,43,False,False,False,False
108956,108956,764,63,2.0,96.885,NaN,NaN,NaN,44,False,False,False,False
108957,108957,764,63,2.0,96.746,NaN,NaN,NaN,45,False,False,False,False
108958,108958,764,63,2.0,96.456,NaN,NaN,NaN,46,False,False,False,False
108959,108959,764,63,2.0,96.708,NaN,NaN,NaN,47,False,False,False,False
108960,108960,764,63,2.0,96.746,NaN,NaN,NaN,48,False,False,False,False
108961,108961,764,63,2.0,97.315,NaN,NaN,NaN,49,False,False,False,False
108962,108962,764,63,2.0,96.973,NaN,NaN,NaN,50,False,False,False,False
108963,108963,764,63,2.0,97.377,NaN,NaN,NaN,51,False,False,False,False
108964,108964,764,63,2.0,97.281,NaN,NaN,NaN,52,False,False,False,False
108965,108965,764,63,2.0,97.412,NaN,NaN,NaN,53,False,False,False,False
108966,108966,764,63,2.0,97.369,NaN,NaN,NaN,54,False,False,False,False
108967,108967,764,63,2.0,97.387,NaN,NaN,NaN,55,False,False,False,False
108968,108968,764,63,2.0,97.844,NaN,NaN,NaN,56,False,False,False,False

In [9]:
mask = (
    (pd.isna(laps_filled["lap_time"])) | 
    (pd.isna(laps_filled["lap_s1_time"])) |
    (pd.isna(laps_filled["lap_s2_time"])) |
    (pd.isna(laps_filled["lap_s3_time"])) 
)

mask = mask & (laps_filled["is_pit_out_lap"] == False)
mask = mask & (pd.isna(laps_filled["lap_s1_time"]))

laps_filled[mask][columns]

,id,session_id,driver_num,position,lap_time,lap_s1_time,lap_s2_time,lap_s3_time,lap_number,is_first_lap,is_last_lap,is_pit_in_lap,is_pit_out_lap
1026,1027,299,9,NaN,NaN,NaN,NaN,NaN,1,True,True,False,False
1905,1906,304,6,NaN,NaN,NaN,NaN,NaN,1,True,True,False,False
1936,1937,304,63,NaN,NaN,NaN,NaN,NaN,31,False,True,False,False
2030,2031,304,77,NaN,NaN,NaN,NaN,NaN,31,False,True,False,False
3203,3204,309,7,NaN,NaN,NaN,NaN,NaN,2,False,True,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
135936,135938,874,18,NaN,NaN,NaN,NaN,NaN,10,False,True,False,False
135937,135939,874,23,NaN,NaN,NaN,NaN,NaN,1,True,True,False,False
136315,136317,874,5,NaN,NaN,NaN,NaN,NaN,1,True,True,False,False
136538,136540,874,81,NaN,NaN,NaN,NaN,NaN,1,True,True,False,False
137701,137703,879,87,NaN,NaN,NaN,NaN,NaN,21,False,True,False,False

Пропуски позиций только на последних кругах, при этом если пропущена позиция, то и пропущено время круга

In [38]:
mask = (
    (~pd.isna(laps_filled["position"])) &  
    (pd.isna(laps_filled["lap_time"]))
)

laps_filled[mask][["session_id", "driver_abbr", "position", "lap_number", "lap_time", "track_status"]]

        session_id driver_abbr  position  lap_number  lap_time  track_status
1059           304         GAS      14.0          33       NaN             5
1123           304         PER       4.0          34       NaN             1
1185           304         ALO      12.0          33       NaN             5
1249           304         LEC       2.0          34       NaN             1
1311           304         STR       7.0          33       NaN             5
...            ...         ...       ...         ...       ...           ...
135584         872         HAD       9.0           1       NaN             2
135603         872         RUS       1.0           1       NaN             2
135622         872         BOT      21.0           1       NaN             2
135634         872         PIA       5.0           1       NaN             2
135653         872         BEA       7.0           1       NaN             2

[876 rows x 6 columns]