In [1]:
from sqlalchemy import create_engine, text
import os
from dotenv import load_dotenv

engine = create_engine(f'postgresql://{os.getenv('DB_USER')}:{os.getenv('DB_PASSWORD')}@localhost:5432/f1pace')

In [2]:
import pandas as pd

In [3]:
tyres = [
    'UNKNOWN',
    'SOFT', 
    'MEDIUM', 
    'HARD', 
    'INTERMEDIATE',
    'WET',
]

track_statuses = {
    1 : 'Track clear',
    2 : 'Yellow flag',
    3 : 'Unknown',
    4 : 'Safity Car',
    5 : 'Red flag',
    6 : 'Virtual Safity Car',
    7 : 'Virtual Safity Car ending',
}

In [4]:
tyres_df = pd.DataFrame(tyres, columns=['name'])
tyres_df

           name
0       UNKNOWN
1          SOFT
2        MEDIUM
3          HARD
4  INTERMEDIATE
5           WET

In [5]:
track_statuses_df = pd.DataFrame.from_dict(track_statuses, orient="index", columns=["name"])
track_statuses_df

                        name
1                Track clear
2                Yellow flag
3                    Unknown
4                 Safity Car
5                   Red flag
6         Virtual Safity Car
7  Virtual Safity Car ending

In [ ]:
tyres_df.to_sql("tyres", engine, index=True, index_label='id', if_exists='append')
track_statuses_df.to_sql("track_statuses", engine, index=True, index_label='id', if_exists='append')

In [6]:
from fastf1 import get_session, set_log_level
import fastf1

# fastf1.Cache.clear_cache()
set_log_level("WARNING")

In [7]:
with engine.connect() as conn:
    cursor = conn.execute(text("select s.id, e.year, e.round, st.name from sessions s join events e on s.event_id = e.id join session_types st on s.session_type = st.id where s.session_type in (5, 7) and e.year > 2020"))
    sessions = cursor.fetchall()
 
sessions

[(299, 2021, 1, 'Race'),
 (304, 2021, 2, 'Race'),
 (309, 2021, 3, 'Race'),
 (314, 2021, 4, 'Race'),
 (319, 2021, 5, 'Race'),
 (324, 2021, 6, 'Race'),
 (329, 2021, 7, 'Race'),
 (334, 2021, 8, 'Race'),
 (339, 2021, 9, 'Race'),
 (343, 2021, 10, 'Sprint'),
 (344, 2021, 10, 'Race'),
 (349, 2021, 11, 'Race'),
 (354, 2021, 12, 'Race'),
 (359, 2021, 13, 'Race'),
 (363, 2021, 14, 'Sprint'),
 (364, 2021, 14, 'Race'),
 (369, 2021, 15, 'Race'),
 (374, 2021, 16, 'Race'),
 (379, 2021, 17, 'Race'),
 (384, 2021, 18, 'Race'),
 (388, 2021, 19, 'Sprint'),
 (389, 2021, 19, 'Race'),
 (394, 2021, 20, 'Race'),
 (399, 2021, 21, 'Race'),
 (404, 2021, 22, 'Race'),
 (409, 2022, 1, 'Race'),
 (414, 2022, 2, 'Race'),
 (419, 2022, 3, 'Race'),
 (423, 2022, 4, 'Sprint'),
 (424, 2022, 4, 'Race'),
 (429, 2022, 5, 'Race'),
 (434, 2022, 6, 'Race'),
 (439, 2022, 7, 'Race'),
 (444, 2022, 8, 'Race'),
 (449, 2022, 9, 'Race'),
 (454, 2022, 10, 'Race'),
 (458, 2022, 11, 'Sprint'),
 (459, 2022, 11, 'Race'),
 (464, 2022, 12, 'Race'),
 (469, 2022, 13, 'Race'),
 (474, 2022, 14, 'Race'),
 (479, 2022, 15, 'Race'),
 (484, 2022, 16, 'Race'),
 (489, 2022, 17, 'Race'),
 (494, 2022, 18, 'Race'),
 (499, 2022, 19, 'Race'),
 (504, 2022, 20, 'Race'),
 (508, 2022, 21, 'Sprint'),
 (509, 2022, 21, 'Race'),
 (514, 2022, 22, 'Race'),
 (519, 2023, 1, 'Race'),
 (524, 2023, 2, 'Race'),
 (529, 2023, 3, 'Race'),
 (533, 2023, 4, 'Sprint'),
 (534, 2023, 4, 'Race'),
 (539, 2023, 5, 'Race'),
 (544, 2023, 6, 'Race'),
 (549, 2023, 7, 'Race'),
 (554, 2023, 8, 'Race'),
 (558, 2023, 9, 'Sprint'),
 (559, 2023, 9, 'Race'),
 (564, 2023, 10, 'Race'),
 (569, 2023, 11, 'Race'),
 (573, 2023, 12, 'Sprint'),
 (574, 2023, 12, 'Race'),
 (579, 2023, 13, 'Race'),
 (584, 2023, 14, 'Race'),
 (589, 2023, 15, 'Race'),
 (594, 2023, 16, 'Race'),
 (598, 2023, 17, 'Sprint'),
 (599, 2023, 17, 'Race'),
 (603, 2023, 18, 'Sprint'),
 (604, 2023, 18, 'Race'),
 (609, 2023, 19, 'Race'),
 (613, 2023, 20, 'Sprint'),
 (614, 2023, 20, 'Race'),
 (619, 2023, 21, 'Race'),
 (624, 2023, 22, 'Race'),
 (629, 2024, 1, 'Race'),
 (634, 2024, 2, 'Race'),
 (639, 2024, 3, 'Race'),
 (644, 2024, 4, 'Race'),
 (647, 2024, 5, 'Sprint'),
 (649, 2024, 5, 'Race'),
 (652, 2024, 6, 'Sprint'),
 (654, 2024, 6, 'Race'),
 (659, 2024, 7, 'Race'),
 (664, 2024, 8, 'Race'),
 (669, 2024, 9, 'Race'),
 (674, 2024, 10, 'Race'),
 (677, 2024, 11, 'Sprint'),
 (679, 2024, 11, 'Race'),
 (684, 2024, 12, 'Race'),
 (689, 2024, 13, 'Race'),
 (694, 2024, 14, 'Race'),
 (699, 2024, 15, 'Race'),
 (704, 2024, 16, 'Race'),
 (709, 2024, 17, 'Race'),
 (714, 2024, 18, 'Race'),
 (717, 2024, 19, 'Sprint'),
 (719, 2024, 19, 'Race'),
 (724, 2024, 20, 'Race'),
 (727, 2024, 21, 'Sprint'),
 (729, 2024, 21, 'Race'),
 (734, 2024, 22, 'Race'),
 (737, 2024, 23, 'Sprint'),
 (739, 2024, 23, 'Race'),
 (744, 2024, 24, 'Race'),
 (749, 2025, 1, 'Race'),
 (752, 2025, 2, 'Sprint'),
 (754, 2025, 2, 'Race'),
 (759, 2025, 3, 'Race'),
 (764, 2025, 4, 'Race'),
 (769, 2025, 5, 'Race'),
 (772, 2025, 6, 'Sprint'),
 (774, 2025, 6, 'Race'),
 (779, 2025, 7, 'Race'),
 (784, 2025, 8, 'Race'),
 (789, 2025, 9, 'Race'),
 (794, 2025, 10, 'Race'),
 (799, 2025, 11, 'Race'),
 (804, 2025, 12, 'Race'),
 (807, 2025, 13, 'Sprint'),
 (809, 2025, 13, 'Race'),
 (814, 2025, 14, 'Race'),
 (819, 2025, 15, 'Race'),
 (824, 2025, 16, 'Race'),
 (829, 2025, 17, 'Race'),
 (834, 2025, 18, 'Race'),
 (837, 2025, 19, 'Sprint'),
 (839, 2025, 19, 'Race'),
 (844, 2025, 20, 'Race'),
 (847, 2025, 21, 'Sprint'),
 (849, 2025, 21, 'Race'),
 (854, 2025, 22, 'Race'),
 (857, 2025, 23, 'Sprint'),
 (859, 2025, 23, 'Race'),
 (864, 2025, 24, 'Race'),
 (869, 2026, 1, 'Race'),
 (872, 2026, 2, 'Sprint'),
 (874, 2026, 2, 'Race'),
 (879, 2026, 3, 'Race'),
 (882, 2026, 4, 'Sprint'),
 (884, 2026, 4, 'Race'),
 (887, 2026, 5, 'Sprint'),
 (889, 2026, 5, 'Race'),
 (894, 2026, 6, 'Race'),
 (899, 2026, 7, 'Race'),
 (904, 2026, 8, 'Race'),
 (907, 2026, 9, 'Sprint'),
 (909, 2026, 9, 'Race'),
 (914, 2026, 10, 'Race'),
 (919, 2026, 11, 'Race'),
 (922, 2026, 12, 'Sprint'),
 (924, 2026, 12, 'Race'),
 (929, 2026, 13, 'Race'),
 (934, 2026, 14, 'Race'),
 (939, 2026, 15, 'Race'),
 (942, 2026, 16, 'Sprint'),
 (944, 2026, 16, 'Race'),
 (949, 2026, 17, 'Race'),
 (954, 2026, 18, 'Race'),
 (959, 2026, 19, 'Race'),
 (964, 2026, 20, 'Race'),
 (969, 2026, 21, 'Race'),
 (974, 2026, 22, 'Race')]

In [13]:
def find_driver(abbr, first_name, last_name):
    abbr = abbr.upper()
    first_name = first_name.capitalize().replace("'", "\'")
    last_name = last_name.capitalize().replace("'", "\'")

    with engine.connect() as conn:
        query = text(f"SELECT id FROM drivers WHERE first_name = :first_name AND last_name = :last_name LIMIT 1")
        cursor = conn.execute(query, {
            "first_name" : first_name, 
            "last_name" : last_name,
        })
        driver_id = cursor.fetchone()
        if driver_id:
            return driver_id[0]
        else:
            query = text("""
                INSERT INTO drivers (abbr, first_name, last_name) 
                VALUES (:abbr, :f_name, :l_name)
            """)
            conn.execute(query, {
                "abbr": abbr, 
                "f_name": first_name, 
                "l_name": last_name
            })
            conn.commit()
            print(f"Created driver {abbr}, {first_name} {last_name}")
            return find_driver(abbr, first_name, last_name)

In [35]:
from fastf1.plotting import get_driver_name

def convert_time(x):
    return x.seconds +  x.microseconds * 1e-6

def convert_tyre(x):
    if not x in tyres:
        return tyres.index("UNKNOWN")
    return tyres.index(x)

def convert_track_status(x):
    priority = [5, 4, 6, 7, 2, 1, 3]
    for p in priority:
        if str(p) in x:
            return p
    return 3

def find_weather(row, weather):
    time1 = row["Time"]
    for i in range(len(weather)):   
        time2 = weather.loc[i, "Time"] 
        if time2 > time1:
            break
    return weather.loc[i][["AirTemp", "TrackTemp", "Humidity", "Rainfall", "WindDirection", "WindSpeed"]]

def get_first_last_name(row, session):
    full_name = get_driver_name(row["Driver"], session)
    return full_name[:full_name.find(' ')], full_name[full_name.find(' ')+1:]


def parce_laps(s_id, year, round, s_type):
    with engine.connect() as conn:
        cursor = conn.execute(text(f"SELECT * FROM laps WHERE session_id = {s_id}"))
        curr_s_laps = cursor.fetchall()

        cursor = conn.execute(text(f"SELECT * FROM weather WHERE session_id = {s_id}"))
        curr_s_weather = cursor.fetchall()

    if len(curr_s_laps)==0:
        session_id = s_id
        session = get_session(year, round, s_type)
        session.load(telemetry=False, laps=True, weather=True)

        laps_df = session.laps[["Time", "Driver", "DriverNumber", 
                                "LapTime", "Sector1Time", "Sector2Time", "Sector3Time", "PitInTime", "PitOutTime",
                                "LapNumber", "Stint", "TyreLife", "Compound", "Deleted", "TrackStatus", "Position"]].copy()


        laps_df["LapTime"] = laps_df["LapTime"].apply(convert_time)
        laps_df["Sector1Time"] = laps_df["Sector1Time"].apply(convert_time)
        laps_df["Sector2Time"] = laps_df["Sector2Time"].apply(convert_time)
        laps_df["Sector3Time"] = laps_df["Sector3Time"].apply(convert_time)
        laps_df["session_time"] = laps_df["Time"].apply(convert_time)
        laps_df["PitInTime"] = laps_df["PitInTime"].apply(convert_time)
        laps_df["PitOutTime"] = laps_df["PitOutTime"].apply(convert_time)

        laps_df["Compound"] = laps_df["Compound"].apply(convert_tyre)
        laps_df["TrackStatus"] = laps_df["TrackStatus"].apply(convert_track_status)
        laps_df["session_id"] = session_id

        laps_df["LapNumber"] = laps_df["LapNumber"].astype('Int64')
        laps_df["TyreLife"] = laps_df["TyreLife"].astype('Int64')
        laps_df["Stint"] = laps_df["Stint"].astype('Int64')
        laps_df["Position"] = laps_df["Position"].astype('Int64')

    

        laps_df[["FirstName", "LastName"]] = laps_df.apply(get_first_last_name, session=session, axis=1, result_type='expand')

        laps_df["driver_id"] = laps_df.apply(
            lambda row : find_driver(row["Driver"], 
                                     row["FirstName"], 
                                     row["LastName"]), 
            axis = 1
        )

        laps_df[["AirTemp", "TrackTemp", "Humidity", 
                "Rainfall", "WindDirection", 
                "WindSpeed"]] = laps_df.apply(find_weather, axis=1, args=(session.weather_data,))
        
        laps_df = (
            laps_df
            .rename(columns={
                "driver_id"    : "driver_id",
                "session_time" : "session_time",
                "PitInTime"    : "pit_in_session_time",
                "PitOutTime"   : "pit_out_session_time",
                "LapTime"      : "lap_time",
                "Sector1Time"  : "lap_s1_time",
                "Sector2Time"  : "lap_s2_time",
                "Sector3Time"  : "lap_s3_time",
                "LapNumber"    : "lap_number",
                "Stint"        : "stint_number",
                "TyreLife"     : "tyre_age",
                "Compound"     : "tyre_type",
                "Deleted"      : "is_deleted",
                "TrackStatus"  : "track_status",
                "Position"     : "position",
            })
        )[["session_id", "driver_id", "position", "session_time", "pit_in_session_time", "pit_out_session_time",
           "lap_time", "lap_s1_time", "lap_s2_time", "lap_s3_time", "lap_number", "stint_number", "tyre_age", 
           "tyre_type", "is_deleted", "track_status"]]

        laps_df.to_sql('laps', engine, index=False, if_exists='append')

    else:
        print(f"Уже есть запись в laps c session_id={s_id}")

    if len(curr_s_weather)==0:
        weather = session.weather_data
        weather["session_time"] = weather["Time"].apply(convert_time)
        weather["session_id"] = session_id
        weather = weather.rename(columns={
            "AirTemp"      : "air_temp", 
            "TrackTemp"    : "track_temp", 
            "Humidity"     : "humidity",
            "Rainfall"     : "is_rain",
            "WindDirection": "wind_direction",
            "WindSpeed"    : "wind_speed",
        })[["session_id", "session_time", "air_temp", "track_temp", "humidity", "is_rain", "wind_direction", "wind_speed"]]

        weather.to_sql('weather', engine, index=False, if_exists='append')
    
    else:
        print(f"Уже есть запись в weather c session_id={s_id}")

In [38]:
from tqdm import tqdm
import time

for s in tqdm(sessions):
    try:
        parce_laps(s[0], s[1], s[2], s[3])

    except Exception as e:
        print(e)
        print(s)

 11%|█▏        | 19/166 [00:00<00:01, 89.22it/s]

Уже есть запись в laps c session_id=299
Уже есть запись в weather c session_id=299
Уже есть запись в laps c session_id=304
Уже есть запись в weather c session_id=304
Уже есть запись в laps c session_id=309
Уже есть запись в weather c session_id=309
Уже есть запись в laps c session_id=314
Уже есть запись в weather c session_id=314
Уже есть запись в laps c session_id=319
Уже есть запись в weather c session_id=319
Уже есть запись в laps c session_id=324
Уже есть запись в weather c session_id=324
Уже есть запись в laps c session_id=329
Уже есть запись в weather c session_id=329
Уже есть запись в laps c session_id=334
Уже есть запись в weather c session_id=334
Уже есть запись в laps c session_id=339
Уже есть запись в weather c session_id=339
Уже есть запись в laps c session_id=343
Уже есть запись в weather c session_id=343
Уже есть запись в laps c session_id=344
Уже есть запись в weather c session_id=344
Уже есть запись в laps c session_id=349
Уже есть запись в weather c session_id=349
Уже есть запись в laps c session_id=354
Уже есть запись в weather c session_id=354
Уже есть запись в laps c session_id=359
Уже есть запись в weather c session_id=359
Уже есть запись в laps c session_id=363
Уже есть запись в weather c session_id=363
Уже есть запись в laps c session_id=364
Уже есть запись в weather c session_id=364
Уже есть запись в laps c session_id=369
Уже есть запись в weather c session_id=369
Уже есть запись в laps c session_id=374
Уже есть запись в weather c session_id=374
Уже есть запись в laps c session_id=379
Уже есть запись в weather c session_id=379

 22%|██▏       | 37/166 [00:00<00:01, 88.49it/s]

Уже есть запись в laps c session_id=384
Уже есть запись в weather c session_id=384
Уже есть запись в laps c session_id=388
Уже есть запись в weather c session_id=388
Уже есть запись в laps c session_id=389
Уже есть запись в weather c session_id=389
Уже есть запись в laps c session_id=394
Уже есть запись в weather c session_id=394
Уже есть запись в laps c session_id=399
Уже есть запись в weather c session_id=399
Уже есть запись в laps c session_id=404
Уже есть запись в weather c session_id=404
Уже есть запись в laps c session_id=409
Уже есть запись в weather c session_id=409
Уже есть запись в laps c session_id=414
Уже есть запись в weather c session_id=414
Уже есть запись в laps c session_id=419
Уже есть запись в weather c session_id=419
Уже есть запись в laps c session_id=423
Уже есть запись в weather c session_id=423
Уже есть запись в laps c session_id=424
Уже есть запись в weather c session_id=424
Уже есть запись в laps c session_id=429
Уже есть запись в weather c session_id=429
Уже есть запись в laps c session_id=434
Уже есть запись в weather c session_id=434
Уже есть запись в laps c session_id=439
Уже есть запись в weather c session_id=439
Уже есть запись в laps c session_id=444
Уже есть запись в weather c session_id=444
Уже есть запись в laps c session_id=449
Уже есть запись в weather c session_id=449
Уже есть запись в laps c session_id=454
Уже есть запись в weather c session_id=454
Уже есть запись в laps c session_id=458
Уже есть запись в weather c session_id=458

 33%|███▎      | 55/166 [00:00<00:01, 89.03it/s]

Уже есть запись в laps c session_id=459
Уже есть запись в weather c session_id=459
Уже есть запись в laps c session_id=464
Уже есть запись в weather c session_id=464
Уже есть запись в laps c session_id=469
Уже есть запись в weather c session_id=469
Уже есть запись в laps c session_id=474
Уже есть запись в weather c session_id=474
Уже есть запись в laps c session_id=479
Уже есть запись в weather c session_id=479
Уже есть запись в laps c session_id=484
Уже есть запись в weather c session_id=484
Уже есть запись в laps c session_id=489
Уже есть запись в weather c session_id=489
Уже есть запись в laps c session_id=494
Уже есть запись в weather c session_id=494
Уже есть запись в laps c session_id=499
Уже есть запись в weather c session_id=499
Уже есть запись в laps c session_id=504
Уже есть запись в weather c session_id=504
Уже есть запись в laps c session_id=508
Уже есть запись в weather c session_id=508
Уже есть запись в laps c session_id=509
Уже есть запись в weather c session_id=509
Уже есть запись в laps c session_id=514
Уже есть запись в weather c session_id=514
Уже есть запись в laps c session_id=519
Уже есть запись в weather c session_id=519
Уже есть запись в laps c session_id=524
Уже есть запись в weather c session_id=524
Уже есть запись в laps c session_id=529
Уже есть запись в weather c session_id=529
Уже есть запись в laps c session_id=533
Уже есть запись в weather c session_id=533
Уже есть запись в laps c session_id=534
Уже есть запись в weather c session_id=534
Уже есть запись в laps c session_id=539
Уже есть запись в weather c session_id=539

 45%|████▍     | 74/166 [00:00<00:01, 89.05it/s]

Уже есть запись в laps c session_id=544
Уже есть запись в weather c session_id=544
Уже есть запись в laps c session_id=549
Уже есть запись в weather c session_id=549
Уже есть запись в laps c session_id=554
Уже есть запись в weather c session_id=554
Уже есть запись в laps c session_id=558
Уже есть запись в weather c session_id=558
Уже есть запись в laps c session_id=559
Уже есть запись в weather c session_id=559
Уже есть запись в laps c session_id=564
Уже есть запись в weather c session_id=564
Уже есть запись в laps c session_id=569
Уже есть запись в weather c session_id=569
Уже есть запись в laps c session_id=573
Уже есть запись в weather c session_id=573
Уже есть запись в laps c session_id=574
Уже есть запись в weather c session_id=574
Уже есть запись в laps c session_id=579
Уже есть запись в weather c session_id=579
Уже есть запись в laps c session_id=584
Уже есть запись в weather c session_id=584
Уже есть запись в laps c session_id=589
Уже есть запись в weather c session_id=589
Уже есть запись в laps c session_id=594
Уже есть запись в weather c session_id=594
Уже есть запись в laps c session_id=598
Уже есть запись в weather c session_id=598
Уже есть запись в laps c session_id=599
Уже есть запись в weather c session_id=599
Уже есть запись в laps c session_id=603
Уже есть запись в weather c session_id=603
Уже есть запись в laps c session_id=604
Уже есть запись в weather c session_id=604
Уже есть запись в laps c session_id=609
Уже есть запись в weather c session_id=609
Уже есть запись в laps c session_id=613
Уже есть запись в weather c session_id=613

 57%|█████▋    | 94/166 [00:01<00:00, 89.65it/s]

Уже есть запись в laps c session_id=614
Уже есть запись в weather c session_id=614
Уже есть запись в laps c session_id=619
Уже есть запись в weather c session_id=619
Уже есть запись в laps c session_id=624
Уже есть запись в weather c session_id=624
Уже есть запись в laps c session_id=629
Уже есть запись в weather c session_id=629
Уже есть запись в laps c session_id=634
Уже есть запись в weather c session_id=634
Уже есть запись в laps c session_id=639
Уже есть запись в weather c session_id=639
Уже есть запись в laps c session_id=644
Уже есть запись в weather c session_id=644
Уже есть запись в laps c session_id=647
Уже есть запись в weather c session_id=647
Уже есть запись в laps c session_id=649
Уже есть запись в weather c session_id=649
Уже есть запись в laps c session_id=652
Уже есть запись в weather c session_id=652
Уже есть запись в laps c session_id=654
Уже есть запись в weather c session_id=654
Уже есть запись в laps c session_id=659
Уже есть запись в weather c session_id=659
Уже есть запись в laps c session_id=664
Уже есть запись в weather c session_id=664
Уже есть запись в laps c session_id=669
Уже есть запись в weather c session_id=669
Уже есть запись в laps c session_id=674
Уже есть запись в weather c session_id=674
Уже есть запись в laps c session_id=677
Уже есть запись в weather c session_id=677
Уже есть запись в laps c session_id=679
Уже есть запись в weather c session_id=679
Уже есть запись в laps c session_id=684
Уже есть запись в weather c session_id=684
Уже есть запись в laps c session_id=689
Уже есть запись в weather c session_id=689

 68%|██████▊   | 113/166 [00:01<00:00, 90.41it/s]

Уже есть запись в laps c session_id=694
Уже есть запись в weather c session_id=694
Уже есть запись в laps c session_id=699
Уже есть запись в weather c session_id=699
Уже есть запись в laps c session_id=704
Уже есть запись в weather c session_id=704
Уже есть запись в laps c session_id=709
Уже есть запись в weather c session_id=709
Уже есть запись в laps c session_id=714
Уже есть запись в weather c session_id=714
Уже есть запись в laps c session_id=717
Уже есть запись в weather c session_id=717
Уже есть запись в laps c session_id=719
Уже есть запись в weather c session_id=719
Уже есть запись в laps c session_id=724
Уже есть запись в weather c session_id=724
Уже есть запись в laps c session_id=727
Уже есть запись в weather c session_id=727
Уже есть запись в laps c session_id=729
Уже есть запись в weather c session_id=729
Уже есть запись в laps c session_id=734
Уже есть запись в weather c session_id=734
Уже есть запись в laps c session_id=737
Уже есть запись в weather c session_id=737
Уже есть запись в laps c session_id=739
Уже есть запись в weather c session_id=739
Уже есть запись в laps c session_id=744
Уже есть запись в weather c session_id=744
Уже есть запись в laps c session_id=749
Уже есть запись в weather c session_id=749
Уже есть запись в laps c session_id=752
Уже есть запись в weather c session_id=752
Уже есть запись в laps c session_id=754
Уже есть запись в weather c session_id=754
Уже есть запись в laps c session_id=759
Уже есть запись в weather c session_id=759
Уже есть запись в laps c session_id=764
Уже есть запись в weather c session_id=764

 74%|███████▍  | 123/166 [00:01<00:00, 90.88it/s]

Уже есть запись в laps c session_id=769
Уже есть запись в weather c session_id=769
Уже есть запись в laps c session_id=772
Уже есть запись в weather c session_id=772
Уже есть запись в laps c session_id=774
Уже есть запись в weather c session_id=774
Уже есть запись в laps c session_id=779
Уже есть запись в weather c session_id=779
Уже есть запись в laps c session_id=784
Уже есть запись в weather c session_id=784
Уже есть запись в laps c session_id=789
Уже есть запись в weather c session_id=789
Уже есть запись в laps c session_id=794
Уже есть запись в weather c session_id=794
Уже есть запись в laps c session_id=799
Уже есть запись в weather c session_id=799
Уже есть запись в laps c session_id=804
Уже есть запись в weather c session_id=804
Уже есть запись в laps c session_id=807
Уже есть запись в weather c session_id=807
Уже есть запись в laps c session_id=809
Уже есть запись в weather c session_id=809
Уже есть запись в laps c session_id=814
Уже есть запись в weather c session_id=814
Уже есть запись в laps c session_id=819
Уже есть запись в weather c session_id=819
Уже есть запись в laps c session_id=824
Уже есть запись в weather c session_id=824
Уже есть запись в laps c session_id=829
Уже есть запись в weather c session_id=829
Уже есть запись в laps c session_id=834
Уже есть запись в weather c session_id=834
Уже есть запись в laps c session_id=837
Уже есть запись в weather c session_id=837
Уже есть запись в laps c session_id=839
Уже есть запись в weather c session_id=839
Уже есть запись в laps c session_id=844
Уже есть запись в weather c session_id=844

 86%|████████▌ | 143/166 [00:01<00:00, 90.51it/s]

Уже есть запись в laps c session_id=847
Уже есть запись в weather c session_id=847
Уже есть запись в laps c session_id=849
Уже есть запись в weather c session_id=849
Уже есть запись в laps c session_id=854
Уже есть запись в weather c session_id=854
Уже есть запись в laps c session_id=857
Уже есть запись в weather c session_id=857
Уже есть запись в laps c session_id=859
Уже есть запись в weather c session_id=859
Уже есть запись в laps c session_id=864
Уже есть запись в weather c session_id=864
Уже есть запись в laps c session_id=869
Уже есть запись в weather c session_id=869
Уже есть запись в laps c session_id=872
Уже есть запись в weather c session_id=872
Уже есть запись в laps c session_id=874
Уже есть запись в weather c session_id=874
Уже есть запись в laps c session_id=879
Уже есть запись в weather c session_id=879
Уже есть запись в laps c session_id=882
Уже есть запись в weather c session_id=882
Уже есть запись в laps c session_id=884
Уже есть запись в weather c session_id=884
any API: 500 calls/h
(887, 2026, 5, 'Sprint')
any API: 500 calls/h
(889, 2026, 5, 'Race')
any API: 500 calls/h
(894, 2026, 6, 'Race')
any API: 500 calls/h
(899, 2026, 7, 'Race')
any API: 500 calls/h
(904, 2026, 8, 'Race')
any API: 500 calls/h
(907, 2026, 9, 'Sprint')
any API: 500 calls/h
(909, 2026, 9, 'Race')
any API: 500 calls/h
(914, 2026, 10, 'Race')

 92%|█████████▏| 153/166 [00:03<00:00, 14.40it/s]

any API: 500 calls/h
(919, 2026, 11, 'Race')
any API: 500 calls/h
(922, 2026, 12, 'Sprint')
any API: 500 calls/h
(924, 2026, 12, 'Race')
any API: 500 calls/h
(929, 2026, 13, 'Race')
any API: 500 calls/h
(934, 2026, 14, 'Race')
any API: 500 calls/h
(939, 2026, 15, 'Race')
any API: 500 calls/h
(942, 2026, 16, 'Sprint')

 96%|█████████▋| 160/166 [00:05<00:00,  8.97it/s]

any API: 500 calls/h
(944, 2026, 16, 'Race')
any API: 500 calls/h
(949, 2026, 17, 'Race')
any API: 500 calls/h
(954, 2026, 18, 'Race')
any API: 500 calls/h
(959, 2026, 19, 'Race')
any API: 500 calls/h
(964, 2026, 20, 'Race')

 99%|█████████▉| 165/166 [00:06<00:00,  7.24it/s]

any API: 500 calls/h
(969, 2026, 21, 'Race')

100%|██████████| 166/166 [00:06<00:00, 24.13it/s]

any API: 500 calls/h
(974, 2026, 22, 'Race')