In [67]:
from sqlalchemy import create_engine, text
import os
from dotenv import load_dotenv

engine = create_engine(f'postgresql://{os.getenv('DB_USER')}:{os.getenv('DB_PASSWORD')}@localhost:5432/f1pace')

In [18]:
from fastf1.ergast import Ergast
import pandas as pd
import time
from tqdm import tqdm

ergast = Ergast()
tracks_df = pd.DataFrame()
for year in tqdm(range(2018, 2027)):
    response_frame = ergast.get_circuits(season=year)
    tracks_df = pd.concat([tracks_df, response_frame], ignore_index=True)
    time.sleep(5)

100%|██████████| 9/9 [00:45<00:00,  5.01s/it]

In [19]:
tracks_df

,circuitId,circuitUrl,circuitName,lat,long,locality,country
0,albert_park,https://en.wikipedia.org/wiki/Albert_Park_Circuit,Albert Park Grand Prix Circuit,-37.8497,144.96800,Melbourne,Australia
1,americas,https://en.wikipedia.org/wiki/Circuit_of_the_A...,Circuit of the Americas,30.1328,-97.64110,Austin,USA
2,bahrain,https://en.wikipedia.org/wiki/Bahrain_Internat...,Bahrain International Circuit,26.0325,50.51060,Sakhir,Bahrain
3,baku,https://en.wikipedia.org/wiki/Baku_City_Circuit,Baku City Circuit,40.3725,49.85330,Baku,Azerbaijan
4,catalunya,https://en.wikipedia.org/wiki/Circuit_de_Barce...,Circuit de Barcelona-Catalunya,41.5700,2.26111,Barcelona,Spain
...,...,...,...,...,...,...,...
188,suzuka,https://en.wikipedia.org/wiki/Suzuka_Internati...,Suzuka Circuit,34.8431,136.54100,Suzuka,Japan
189,vegas,https://en.wikipedia.org/wiki/Las_Vegas_Grand_...,Las Vegas Strip Street Circuit,36.1147,-115.17300,Las Vegas,USA
190,villeneuve,https://en.wikipedia.org/wiki/Circuit_Gilles_V...,Circuit Gilles Villeneuve,45.5000,-73.52280,Montreal,Canada
191,yas_marina,https://en.wikipedia.org/wiki/Yas_Marina_Circuit,Yas Marina Circuit,24.4672,54.60310,Abu Dhabi,UAE
192,zandvoort,https://en.wikipedia.org/wiki/Circuit_Zandvoort,Circuit Park Zandvoort,52.3888,4.54092,Zandvoort,Netherlands

In [ ]:
tracks_df_clean = (
    tracks_df[["circuitId", "country", "locality", "circuitName", "lat", "long"]]
    .drop_duplicates(subset="circuitId")
    .reset_index(drop=True)
    .rename(columns={"locality" : "location",
                     "circuitId": "circuit_id",
                     "circuitName": "circuit_name"})
)
tracks_df_clean

,circuit_id,country,location,circuit_name,lat,long
0,albert_park,Australia,Melbourne,Albert Park Grand Prix Circuit,-37.84970,144.96800
1,americas,USA,Austin,Circuit of the Americas,30.13280,-97.64110
2,bahrain,Bahrain,Sakhir,Bahrain International Circuit,26.03250,50.51060
3,baku,Azerbaijan,Baku,Baku City Circuit,40.37250,49.85330
4,catalunya,Spain,Barcelona,Circuit de Barcelona-Catalunya,41.57000,2.26111
5,hockenheimring,Germany,Hockenheim,Hockenheimring,49.32780,8.56583
6,hungaroring,Hungary,Budapest,Hungaroring,47.57890,19.24860
7,interlagos,Brazil,São Paulo,Autódromo José Carlos Pace,-23.70360,-46.69970
8,marina_bay,Singapore,Marina Bay,Marina Bay Street Circuit,1.29140,103.86400
9,monaco,Monaco,Monte Carlo,Circuit de Monaco,43.73470,7.42056
10,monza,Italy,Monza,Autodromo Nazionale di Monza,45.61560,9.28111
11,red_bull_ring,Austria,Spielberg,Red Bull Ring,47.21970,14.76470
12,ricard,France,Le Castellet,Circuit Paul Ricard,43.25060,5.79167
13,rodriguez,Mexico,Mexico City,Autódromo Hermanos Rodríguez,19.40420,-99.09070
14,shanghai,China,Shanghai,Shanghai International Circuit,31.33890,121.22000
15,silverstone,UK,Silverstone,Silverstone Circuit,52.07860,-1.01694
16,sochi,Russia,Sochi,Sochi Autodrom,43.40570,39.95780
17,spa,Belgium,Spa,Circuit de Spa-Francorchamps,50.43720,5.97139
18,suzuka,Japan,Suzuka,Suzuka Circuit,34.84310,136.54100
19,villeneuve,Canada,Montreal,Circuit Gilles Villeneuve,45.50000,-73.52280
20,yas_marina,UAE,Abu Dhabi,Yas Marina Circuit,24.46720,54.60310
21,imola,Italy,Imola,Autodromo Enzo e Dino Ferrari,44.34390,11.71670
22,istanbul,Turkey,Istanbul,Istanbul Park,40.95170,29.40500
23,mugello,Italy,Mugello,Autodromo Internazionale del Mugello,43.99750,11.37190
24,nurburgring,Germany,Nürburg,Nürburgring,50.33560,6.94750
25,portimao,Portugal,Portimão,Autódromo Internacional do Algarve,37.22700,-8.62670
26,jeddah,Saudi Arabia,Jeddah,Jeddah Corniche Circuit,21.63190,39.10440
27,losail,Qatar,Lusail,Losail International Circuit,25.49000,51.45420
28,zandvoort,Netherlands,Zandvoort,Circuit Park Zandvoort,52.38880,4.54092
29,miami,USA,Miami,Miami International Autodrome,25.95810,-80.23890
30,vegas,USA,Las Vegas,Las Vegas Strip Street Circuit,36.11470,-115.17300
31,madring,Spain,Madrid,Madring,40.46528,-3.61528

In [64]:
with engine.connect() as conn:
    conn.execute(text("DELETE FROM tracks"))
    conn.commit()

tracks_df_clean.to_sql("tracks", engine, if_exists="append", index=True, index_label="id")

32

In [65]:
with engine.connect() as conn:
    cursor = conn.execute(text("SELECT * FROM tracks"))
    print(cursor.fetchall())

[(0, 'albert_park', 'Australia', 'Melbourne', 'Albert Park Grand Prix Circuit', -37.8497, 144.968), (1, 'americas', 'USA', 'Austin', 'Circuit of the Americas', 30.1328, -97.6411), (2, 'bahrain', 'Bahrain', 'Sakhir', 'Bahrain International Circuit', 26.0325, 50.5106), (3, 'baku', 'Azerbaijan', 'Baku', 'Baku City Circuit', 40.3725, 49.8533), (4, 'catalunya', 'Spain', 'Barcelona', 'Circuit de Barcelona-Catalunya', 41.57, 2.26111), (5, 'hockenheimring', 'Germany', 'Hockenheim', 'Hockenheimring', 49.3278, 8.56583), (6, 'hungaroring', 'Hungary', 'Budapest', 'Hungaroring', 47.5789, 19.2486), (7, 'interlagos', 'Brazil', 'São Paulo', 'Autódromo José Carlos Pace', -23.7036, -46.6997), (8, 'marina_bay', 'Singapore', 'Marina Bay', 'Marina Bay Street Circuit', 1.2914, 103.864), (9, 'monaco', 'Monaco', 'Monte Carlo', 'Circuit de Monaco', 43.7347, 7.42056), (10, 'monza', 'Italy', 'Monza', 'Autodromo Nazionale di Monza', 45.6156, 9.28111), (11, 'red_bull_ring', 'Austria', 'Spielberg', 'Red Bull Ring', 47.2197, 14.7647), (12, 'ricard', 'France', 'Le Castellet', 'Circuit Paul Ricard', 43.2506, 5.79167), (13, 'rodriguez', 'Mexico', 'Mexico City', 'Autódromo Hermanos Rodríguez', 19.4042, -99.0907), (14, 'shanghai', 'China', 'Shanghai', 'Shanghai International Circuit', 31.3389, 121.22), (15, 'silverstone', 'UK', 'Silverstone', 'Silverstone Circuit', 52.0786, -1.01694), (16, 'sochi', 'Russia', 'Sochi', 'Sochi Autodrom', 43.4057, 39.9578), (17, 'spa', 'Belgium', 'Spa', 'Circuit de Spa-Francorchamps', 50.4372, 5.97139), (18, 'suzuka', 'Japan', 'Suzuka', 'Suzuka Circuit', 34.8431, 136.541), (19, 'villeneuve', 'Canada', 'Montreal', 'Circuit Gilles Villeneuve', 45.5, -73.5228), (20, 'yas_marina', 'UAE', 'Abu Dhabi', 'Yas Marina Circuit', 24.4672, 54.6031), (21, 'imola', 'Italy', 'Imola', 'Autodromo Enzo e Dino Ferrari', 44.3439, 11.7167), (22, 'istanbul', 'Turkey', 'Istanbul', 'Istanbul Park', 40.9517, 29.405), (23, 'mugello', 'Italy', 'Mugello', 'Autodromo Internazionale del Mugello', 43.9975, 11.3719), (24, 'nurburgring', 'Germany', 'Nürburg', 'Nürburgring', 50.3356, 6.9475), (25, 'portimao', 'Portugal', 'Portimão', 'Autódromo Internacional do Algarve', 37.227, -8.6267), (26, 'jeddah', 'Saudi Arabia', 'Jeddah', 'Jeddah Corniche Circuit', 21.6319, 39.1044), (27, 'losail', 'Qatar', 'Lusail', 'Losail International Circuit', 25.49, 51.4542), (28, 'zandvoort', 'Netherlands', 'Zandvoort', 'Circuit Park Zandvoort', 52.3888, 4.54092), (29, 'miami', 'USA', 'Miami', 'Miami International Autodrome', 25.9581, -80.2389), (30, 'vegas', 'USA', 'Las Vegas', 'Las Vegas Strip Street Circuit', 36.1147, -115.173), (31, 'madring', 'Spain', 'Madrid', 'Madring', 40.46528, -3.61528)]